Removed reference to HoloLens to resolve build error
After getting latest and trying to build with 5.3 received the following errors.
Assuming this is related to the OpenXR changes in 5.3.
Removing the references to HoloLens resolved the issue.
1>Invalidating makefile for PlaygroundEditor (HttpGPT.uplugin has been added)
1>E:\UE5\Playground\Plugins\UEHttpGPT\HttpGPT.uplugin : warning : Unknown platform HoloLens while parsing allow list for module descriptor HttpGPTChatModule
1>E:\UE5\Playground\Plugins\UEHttpGPT\HttpGPT.uplugin : warning : Unknown platform HoloLens while parsing allow list for module descriptor HttpGPTImageModule
1>E:\UE5\Playground\Plugins\UEHttpGPT\HttpGPT.uplugin : warning : Unknown platform HoloLens while parsing allow list for module descriptor HttpGPTCommonModule
1>Compiled assembly file 'E:\UE5\Playground\Intermediate\Build\BuildRules\PlaygroundModuleRules.dll' appears to be for a newer CLR version or is otherwise invalid.  Unreal Build Tool will try to recompile this assembly now.  (Exception: Could not load file or assembly 'E:\UE5\Playground\Intermediate\Build\BuildRules\PlaygroundModuleRules.dll'. Format of the executable (.exe) or library (.dll) is invalid.)
1>E:\UE5\Playground\Plugins\UEHttpGPT\Source\HttpGPTChatModule\HttpGPTChatModule.Build.cs(14,53): error CS0117: 'UnrealTargetPlatform' does not contain a definition for 'HoloLens'
1>E:\UE5\Playground\Plugins\UEHttpGPT\Source\HttpGPTCommonModule\HttpGPTCommonModule.Build.cs(14,53): error CS0117: 'UnrealTargetPlatform' does not contain a definition for 'HoloLens'
1>E:\UE5\Playground\Plugins\UEHttpGPT\Source\HttpGPTEditorModule\HttpGPTEditorModule.Build.cs(15,53): error CS0117: 'UnrealTargetPlatform' does not contain a definition for 'HoloLens'
1>E:\UE5\Playground\Plugins\UEHttpGPT\Source\HttpGPTImageModule\HttpGPTImageModule.Build.cs(14,53): error CS0117: 'UnrealTargetPlatform' does not contain a definition for 'HoloLens'